<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>5a3f7704-3dab-4bce-832c-43b5e0e19c6e</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
		<ExcludeFromCodeCoverage>true</ExcludeFromCodeCoverage>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Http" />
		<PackageReference Include="Asp.Versioning.Mvc" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
		<PackageReference Include="Aspire.Npgsql" />
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Aspire.StackExchange.Redis" />
		<PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" />
		<PackageReference Include="Bogus" />
		<PackageReference Include="linq2db.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
		<PackageReference Include="Scalar.AspNetCore" />
		<PackageReference Include="Scalar.AspNetCore.Microsoft" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\HypermediaEngine\AspNetCore\HypermediaEngine.AspNetCore.csproj" />
	</ItemGroup>

</Project>
