<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<AssemblyName>$(AssemblyName).IntegrationTests</AssemblyName>
		<RootNamespace>HypermediaEngine.IntegrationTests</RootNamespace>
		<IsTestProject>true</IsTestProject>
		<ExcludeFromCodeCoverage>true</ExcludeFromCodeCoverage>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Microsoft.AspNetCore.TestHost" />
		<PackageReference Include="Testcontainers.PostgreSql" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\samples\DotNetRestAPI\DotNetRestAPI.csproj" />
	</ItemGroup>

</Project>
